---
title: "Statistical Modeling with R and Stan"
output: 
  learnr::tutorial:
    css: css/learnr-theme.css
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
if ("learnr" %in% (.packages()))
  detach(package:learnr, unload = TRUE)
library(learnr)
knitr::opts_chunk$set(echo = FALSE)

## Save package names as a vector of strings
pkgs <-  c()

## Install uninstalled packages
lapply(pkgs[!(pkgs %in% installed.packages())], 
       install.packages,
       repos='http://cran.us.r-project.org')

## Load all packages to library and adjust options
lapply(pkgs, library, character.only = TRUE)
```

## Hi, I'm Denis!

- 

## Who are you?

- 

## Statistical Modeling with R and Stan

### Primary Learning Objectives

1. Understand generalized linear models as a common theoretical framework for statistical models
1. Understand how to process estimates from generalized linear models into substantively meaningful quantities of interest *without* relying on pre-implemented software
1. Understand how to use distributional summaries as a flexible framework for reporting inferential uncertainty
1. *Applied* Bayesian statistics: Learn how to translate formal statistical models into code using Stan

### Secondary Learning Objectives

1. Bump up your programming skills
1. Bump up your understanding of probability theory
1. Bum up your data visualization skills
1. *Theoretical* Bayesian statistics: Learn about fundamentals concepts of Bayesian statistics

## Schedule

| Session | Time                           | Topics                                                                                                     |
|:-------:|:-------------------------------|:-----------------------------------------------------------------------------------------------------------|
| 1       | Day 1, 09:00-11:00             | **R Math & Programming Refresher**                                                                         |
|         |                                | 1. Good coding practices                                                                                   |
|         |                                | 2. Object types and conversions; slicing and indexing                                                      |
|         |                                | 3. Control structures                                                                                      |
|         |                                | 4. Probability distributions                                                                               |
|         |                                | 5. Linear algebra                                                                                          |
| 2       | Day 1, 11:00-13:00             | **Generalized Linear Models**                                                                              |
|         |                                | 1. GLM basics: Systematic component, link function, family/likelihood; model matrix, coefficient vector    |
|         |                                | 2. The simulation approach                                                                                 |
|         |                                | 3. Quantities of interest (definition, calculation, simulation)                                            |
| 3       | Day 1, 14:00-16:00             | **Bayesian Fundamentals**                                                                                  |
|         |                                | 1. Fundamental concepts: Prior distribution, likelihood, posterior distribution                            |
|         |                                | 2. MCMC Algorithms                                                                                         |
| 4       | Day 2, 09:00-11:00             | **Applied Bayesian Statistics Using Stan: Basics** (Application: Linear Model)                             |
|         |                                | 1. Stan: Language, documentation, and core program blocks                                                  |
|         |                                | 2. The Bayesian workflow                                                                                   |
| 5       | Day 2, 11:00-13:00             | **Applied Bayesian Statistics Using Stan: Extensions** (Application: Binary Choice Models)                 |
|         |                                | 1. Optional Stan program blocks: Functions, transformed data, transformed parameters, generated quantities |
|         |                                | 2. Efficiency tuning                                                                                       |
|         |                                | 3. Processing posterior draws in Stan and R                                                                |
| 6       | Day 2, 14:00-16:00             | **Applied Bayesian Statistics Using Stan: Advanced Modeling**                                              |
|         |                                | 1. Measurement models                                                                                      |
|         |                                | 2. Hierarchical models                                                                                     |
|         |                                | 3. Systems of equations                                                                                    |

## Structure of our sessions

We have 120 minutes per session. We will flexibly divide each session into the following sequence:

1. Lecture
2. Hands-on exercises (breakout rooms, in teams of two)
3. Discussing solutions to exercises
4. Breaks

## Feedback

While bits and pieces of the teaching materials existed before, much of this
workshop is a first. Feel free to share your feedback at any time, especially
when you have suggestions that we can accommdate on the fly.

## Questions?




